export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: '#0a0a0f', color: '#f0f0f5' }}>
      <header style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2">
            <span className="text-lg font-bold text-white">Pulsed</span>
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400"></span>
          </a>
          <a href="/signup" className="inline-flex items-center px-4 py-2 text-sm font-medium text-white rounded-lg hover:opacity-90 transition-opacity" style={{ background: 'linear-gradient(135deg, #6366f1, #8b5cf6)' }}>
            Get Started
          </a>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 pt-10 pb-16">
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-sm mb-10" style={{ color: '#6b6b80' }}>Last updated: February 14, 2026</p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: '#8b8b9e' }}>
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Pulsed (&quot;the Service&quot;), operated by Pulsed (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>Pulsed is an AI-powered research and automation platform. The Service provides AI agents that perform research, generate briefs, and automate tasks using large language models (LLMs). Users may connect their own API keys from third-party AI providers (&quot;BYOLLM&quot; — Bring Your Own LLM).</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. Accounts</h2>
            <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials and API keys. You are responsible for all activity that occurs under your account.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. BYOLLM &amp; API Keys</h2>
            <p>When you provide your own API keys, you are responsible for all usage and costs incurred with the respective AI provider. We do not mark up, resell, or profit from your API key usage. Your API keys are encrypted at rest and never shared with third parties. You may revoke your API keys at any time through your provider&apos;s dashboard.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Subscriptions &amp; Billing</h2>
            <p>Pulsed offers free and paid tiers. Paid subscriptions are billed monthly through Stripe. You may cancel at any time; your subscription will remain active until the end of the current billing period. Refunds are handled on a case-by-case basis.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Acceptable Use</h2>
            <p>You agree not to use the Service to: (a) violate any laws or regulations; (b) generate harmful, abusive, or misleading content; (c) attempt to reverse-engineer or exploit the Service; (d) use automated systems to create accounts or abuse free tier limits; (e) transmit malware or interfere with the Service&apos;s operation.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Intellectual Property</h2>
            <p>Content generated by your AI agent using your API keys belongs to you. The Pulsed platform, branding, and proprietary features remain our intellectual property. Research briefs generated using our free tier research engine may be shared publicly with attribution.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Disclaimers</h2>
            <p>The Service is provided &quot;as is&quot; without warranties of any kind. AI-generated content may contain inaccuracies. We do not guarantee the accuracy, completeness, or reliability of any research briefs or AI outputs. You are responsible for verifying any information before acting on it.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Pulsed shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to loss of data, revenue, or business opportunities.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Termination</h2>
            <p>We may suspend or terminate your account at any time for violation of these terms. You may delete your account at any time. Upon termination, your data will be deleted within 30 days unless required by law.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">11. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms. We will notify users of material changes via email or in-app notification.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">12. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:hello@runpulsed.ai" className="text-indigo-400 hover:text-indigo-300">hello@runpulsed.ai</a>.</p>
          </section>
        </div>
      </main>

      <footer className="py-8 text-center text-xs" style={{ color: '#6b6b80', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
        <p>&copy; 2026 Pulsed. All rights reserved. &middot; <a href="/privacy" className="hover:text-white transition-colors">Privacy</a> &middot; <a href="/terms" className="hover:text-white transition-colors">Terms</a></p>
      </footer>
    </div>
  );
}
